name: Pull Request Validation

on:
  pull_request:
    branches: 
    - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: chmod +x ./gradlew
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build test
